# *********************************************************
# Configuration file of Pharmbox spring-boot application
# Development technical configuration
# *********************************************************

spring:
  application:
    name: pharmbox
  main:
    allow-bean-definition-overriding: true
  jmx: enabled=false
  server:
    port: 8080
    shutdown: graceful

  # database
  jpa:
    show-sql: true
    open-in-view: false
    repositories:
      bootstrap-mode: deferred
    datasource:
      hikari.auto-commit: false
    hibernate:
      ddl-auto: validate
    #spring.jpa.properties.hibernate.format_sql=true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
          optimizer:
            pooled:
              preferred: pooled-lo
        generate_statistics: false
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        connection:
          provider_disables_autocommit: true
    flyway:
      enabled: false
      encoding: UTF-8
      locations: classpath:db/migration/{vendor}
      validate-on-migrate: false
      schemas:
        - pharmbox

  ################ Logging #####################
logging:
  file:
    name: logs/pharmbox.log
  level:
    web: INFO
    sql: INFO

  ## To enable transaction details logging
  #logging.level.org.springframework.orm.jpa=DEBUG
  #logging.level.org.springframework.transaction=DEBUG
  #logging.level.org.hibernate.engine.transaction.internal.TransactionImpl=DEBUG

  ################ Actuator #####################

management:
  server:
    port: 8444
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude:
          - "*"
    web:
      base-path: /actuator
      exposure:
        include: configprops,env,health,info,logfile,loggers,metrics
  endpoint:
    info:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: always

